# Port for local testing
server.port: 8086

server:
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: false

  # Enabling http2 should increase performance in most cases, but best to check if it really does
  # Note that it only works when using https.
  http2:
    enabled: true

  compression:
    enabled: true
    min-response-size: 4096
    mime-types: application/json, application/ld+json, application/xml, text/html, text/xml, text/plain

management:
  endpoints:
    web:
      exposure:
        include: info

  info:
    env:
      enabled: true


