auth.api.name           =
auth.token.endpoint     =
auth.token.signature    =
auth.token.grant.params =
auth.apikey.endpoint    =

# Enable a default seeAlso field with the line below
server.error.see-also = https://api.europeana.eu