resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: myapi

# expects files to be in the same directory
secretGenerator:
  - name: myapi-secret
    files:
      - myapi.user.properties
