resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: api-template

# expects files to be in the same directory
secretGenerator:
  - name: api-template-secret
    files:
      - myapi.user.properties
