apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
spec:
  template:
    spec:
      containers:
        - name: api-template
          # required to use local image
          imagePullPolicy: Never