apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  template:
    spec:
      containers:
        - name: myapi
          # required to use local image
          imagePullPolicy: Never